### ISSUE TITLE
ContextMenu 显示位置距离鼠标太远

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#119]
https://github.com/Hakoyu/StarsectorTools/issues/4

**Comment by Mochengvia** [comment]
此问题已经确认，但由于WPF的机制问题，暂时无法修复。
延期处理。

**Comment by Mochengvia** [comment]
此问题应当已在历史版本中修复。
由于时间太久，关闭此issue
