### ISSUE TITLE
[新特性] WindowX的Win11下的SnapLayout的支持

### ISSUE THREAD

**Issue by emako** [Panuon/Panuon.WPF.UI#146]
翻了一下源码，应该是没有支持SnapLayout的，SnapLayout可参考
官方文档：https://learn.microsoft.com/zh-cn/windows/apps/desktop/modernize/apply-snap-layout-menu
和这个库的实现：https://github.com/Simnico99/MicaWPF/blob/main/src/MicaWPF/Controls/MicaWindow.cs

**Comment by Mochengvia** [comment]
反馈已收到。这个功能将在下一个大版本中推出。
