### ISSUE TITLE
Popup在窗口移动以后不会跟随窗口移动

### ISSUE THREAD

**Issue by yangf85** [Panuon/Panuon.WPF.UI#152]
https://blog.csdn.net/qq_43024228/article/details/110353099

**Comment by fanbal** [comment]
在WPF中Popup就是这样的，复杂的解决办法就是上面用Win32，简单的方法那就 Popup.StaysOpen = false，在拖的时候Popup直接消失，这样就不会发现窗口跟随移动的破绽了
