### ISSUE TITLE
1.1.11.8 更新后，pu:GroupBoxHelper.HeaderHeight失效

### ISSUE THREAD

**Issue by Minstreams** [Panuon/Panuon.WPF.UI#167]
定义一个 GroupBox 和一个 Expander ，如下
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/32974920/65af5f06-6fe7-4baa-a26a-398cdcc8b018)
结果 Expander 的 headerHeight 符合预期，GroupBox 的 headerHeght 不生效
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/32974920/d8ae8621-4296-449a-9475-10607e1d609e)

**Comment by Mochengvia** [comment]
此问题将在今天的版本中修复。

**Comment by Mochengvia** [comment]
此问题已在1.1.11.9中修复。
如果有其他问题，请重新打开此issue。
