### ISSUE TITLE
 pu:TextBoxHelper.InputLimit="UpperCaseLetters, MultipleSpaces"  有问题

### ISSUE THREAD

**Issue by Pomelo2021** [Panuon/Panuon.WPF.UI#170]
大小写反了，MultipleSpaces没有效果， .net 4.8

**Comment by Pomelo2021** [comment]
![微信图片_20230602142708](https://github.com/Panuon/Panuon.WPF.UI/assets/88882927/72865e76-1ba5-4996-a48c-10584bb4b6bb)
输入和粘贴事件里都是反的

**Comment by Pomelo2021** [comment]
foreach (var inputChar in e.Text)
            {
                if ((inputLimit.HasFlag(InputLimits.Digit)
                     && inputChar >= 48 && inputChar <= 57) ||
                   (inputLimit.HasFlag(InputLimits.UpperCaseLetters)
                     && inputChar >= 97 && inputChar <= 122) ||
                   (inputLimit.HasFlag(InputLimits.LowerCaseLetters)
                     && inputChar >= 65 && inputChar <= 90) ||
                   (inputLimit.HasFlag(InputLimits.Point)
                     && inputChar == '.' && !text.Contains(".")) ||
                   (inputLimit.HasFlag(InputLimits.At)
                     && inputChar == '@' && !text.Contains("@")) ||
                   (inputLimit.HasFlag(InputLimits.MultiplePoints)
                     && inputChar == '.') ||
                   (inputLimit.HasFlag(InputLimits.MultipleAts)
                     && inputChar == '@'))
                {
                    text += inputChar;
                }
                else
                {
                    e.Handled = true;
                    return;
                }
            }

输入和粘贴事件里面都反了

**Comment by Mochengvia** [comment]
此问题已经确认，将在最近的版本中修复。

**Comment by Mochengvia** [comment]
问题已经修复
