### ISSUE TITLE
TextBox使用中文输入法，若正在向Focused态过渡时打字，会抛System.InvalidCastException异常

### ISSUE THREAD

**Issue by Minstreams** [Panuon/Panuon.WPF.UI#174]
NuGet包版本1.1.11.12，复现流程：
1. 定义两个SolidColorBrush
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/32974920/ee5a79ba-e6d0-4c15-8727-320035bac9b7)
2. 定义一个Style，其中Foreground和pu:TextBoxHelper.FocusedForeground设定不同值
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/32974920/4d5cd5db-2366-42fd-a699-1d3c8bca07b4)
3. 随便建一个TextBox，运行
4. 切到中文输入法（我用的Win10自带的微软拼音），鼠标点这个TextBox，在其完全过渡到Focused态前，迅速输入任意字母
5. 引发System.InvalidCastException异常
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/32974920/f47d7bdf-ea36-4e51-a47b-1599f98cef82)

**Comment by Mochengvia** [comment]
这个问题有收到过反馈，但很遗憾目前无法解决。
目前应该只有微软拼音输入法会导致这个问题。
如果一定要设置选中前景色，可以尝试将 `GlobalSettings` 中的 `AnimationDuration` 属性设置为更低的值，或直接使用Setter来解决。
