### ISSUE TITLE
使 ShadowColor 支持 SolidColorBrush

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#176]
目前 `ShadowColor` 不支持 `SolidColorBrush` 只支持 `Color`

![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/7ab8e30d-2146-4fb2-b22b-0b0e5beb4253)

**Orionid** 生成的代码也直接引用的是 `SolidColorBrush`

**Comment by Mochengvia** [comment]
这个问题无法解决。  
WPF的 `DropShadowEffect` 效果类型只接受 `Color` 类型的值，因此无法让pu中的 `ShadowColor` 支持 `SolidColorBrush` 。

**Comment by Hakoyu** [comment]
也不是不行啊 就是这玩意得算中断性更改了

![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/a130ca4f-aea9-4ebf-b847-a8fb0d14798e)
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/476b0ec0-7822-4b34-aeeb-2b01cdc21c2b)
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/45b1c102-cfdb-4ba5-b7ec-9224fb1fdac6)
