### ISSUE TITLE
PasswordBoxHelper.PlainButton 添加可切换显示选项

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#177]
例如:
`pu:PasswordBoxHelper.PlainButtonIsToggle`

**Comment by Mochengvia** [comment]
PasswordBox不支持以明文的方式编辑，按下显示按钮时显示出来的是TextBlock而非TextBox

**Comment by Hakoyu** [comment]
说得对 这么改还是有些欠妥
