### ISSUE TITLE
MessageBoxX倒计时返回的MessageBoxResult为None

### ISSUE THREAD

**Issue by superman756** [Panuon/Panuon.WPF.UI#180]
MessageBoxX.Show(this, "MessageBoxX style configuration is placed in App.xaml. ", "Tips", MessageBoxIcon.Info, DefaultButton.YesOK, 5);

我在之前的Panuon.UI.Silver 2.2.19.0功能是正常的，使用Panuon.WPF.UI最新版发现MessageBoxX.Show如果不选择的话，只会返回none，请问可以处理下吗？

**Comment by Mochengvia** [comment]
此问题已在1.1.15.1中修复
