### ISSUE TITLE
同时设置 ListBoxHelper.ItemsHoverShadowColor 和 ListBoxHelper.ItemsSelectedShadowColor 会有冲突

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#185]
# 只设置 `ListBoxHelper.ItemsSelectedShadowColor`
![Honeycam 2023-07-22 18-20-05](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/b0fe05fb-b6df-41f6-b55f-a3de69e23ce2)

# 同时设置 `ListBoxHelper.ItemsHoverShadowColor` 和 `ListBoxHelper.ItemsSelectedShadowColor`
会导致 `ListBoxHelper.ItemsSelectedShadowColor` 效果无法正常显示
![Honeycam 2023-07-22 18-19-33](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/6ab23e89-7180-4e14-b08a-3c272c1fc58d)

**Comment by Mochengvia** [comment]
此问题已修复，将在下个版本中更新
