### ISSUE TITLE
建议: 新增 PasswordBoxHelper.IsReadOnly

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#187]
可以将 `PasswordBox` 设置为只读模式
并非只有输入密码才能用 `PasswordBox` 
配合上 `PlainButton` 的功能也可以用于显示敏感信息(如序列码等)

**Comment by Mochengvia** [comment]
可行
此功能已作为 `IsReadOnly` 属性添加，将在下个版本发布中提供
