### ISSUE TITLE
ComboBoxItemStyle 全局设置不起作用 ?

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#188]
![Honeycam 2023-07-26 16-38-55](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/565a6f33-eafc-46c7-9207-9863499db631)

**Comment by Mochengvia** [comment]
ComboBoxItemStyle只能在某个ComboBox上设置。要修改所有ComboBox的Item效果，应该重写ComboBox的样式而不是ComboBoxItem

**Comment by Mochengvia** [comment]
https://github.com/Panuon/Panuon.WPF.UI/wiki/Contract-zh-CN#%E6%B4%BE%E7%94%9F%E8%87%AAitemscontrol%E7%9A%84%E6%8E%A7%E4%BB%B6

**Comment by Hakoyu** [comment]
我是想把 `ComboBox` 和 `ComboBoxItem` 的设置分开以便区分
比较好的做法大概是设置 `ItemContainerStyle`
每个都这么写的话 会麻烦一点

因为 `ListBox` 和 `ListBoxItem` 分开写是可以生效的
所以我对此抱有疑问

**Comment by Mochengvia** [comment]
没有太懂你的意思
如果要修改单个ComboBox中所有ComboBoxItem的选中背景色，只需要在ComboBox上添加`pu:ComboBoxHelper.ItemsSelectedBackground="Red"` 就可以
另外，在ComboBox上写`ItemContainerStyle` 并设置 `BasedOn="{StaticResource {x:Type ComboBoxItem}}"` 然后再写Trigger或Setter也能达到同样的效果

**Comment by Mochengvia** [comment]
是出于什么原因需要单独设置ComboBoxItem呢，在ComboBox之外的地方不应该会用到ComboBoxItem

**Comment by Mochengvia** [comment]
<Style x:Key="ComboBoxItemStyle" TargetType="ComboBoxItem" BasedOn="{StaticResource {x:Type ComboBoxItem}}">
..
然后在ComboBox上设置 `ItemContainerStyle="{StaticResource ComboBoxItemStyle}"` 也可以

**Comment by Hakoyu** [comment]
> 是出于什么原因需要单独设置ComboBoxItem呢，在ComboBox之外的地方不应该会用到ComboBoxItem

没别的原因 只是将它们分开以便管理

**Comment by Hakoyu** [comment]
> <Style x:Key="ComboBoxItemStyle" TargetType="ComboBoxItem" BasedOn="{StaticResource {x:Type ComboBoxItem}}"> .. 然后在ComboBox上设置 `ItemContainerStyle="{StaticResource ComboBoxItemStyle}"` 也可以

是的 现在就是使用的这种方式
