### ISSUE TITLE
NumberInput 在控件上修改时无法触发 Value 的绑定值

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#189]
![Honeycam 2023-08-25 17-37-03](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/c61bd2be-49cf-47fa-ab8b-1ecd4b2fb3e5)

**Comment by Hakoyu** [comment]
后台对绑定值的修改可以触发 但前台不行

**Comment by Mochengvia** [comment]
我在Samples项目中新建了一个NumberInput
![图片](https://github.com/Panuon/Panuon.WPF.UI/assets/23360265/b4224b98-e1a9-4107-959e-1971161508ae)
![图片](https://github.com/Panuon/Panuon.WPF.UI/assets/23360265/180c690e-720b-403c-9237-7b2f06791bee)
一切正常，你能提供无法触发的示例吗？

**Comment by Mochengvia** [comment]
如果你是绑定到Value上，确保加了Mode=TwoWay

**Comment by Hakoyu** [comment]
> 如果你是绑定到Value上，确保加了Mode=TwoWay

确实 必须要添加 `Mode=TwoWay` 才能触发 `PropertyChanged`

**Comment by Mochengvia** [comment]
下个版本会添加默认的TwoWay绑定
