### ISSUE TITLE
在窗口设置为IsDragMoveArea="True"时，Slider无法正常滑动只能点击。并且设置项目DisableDragMove的优先级低于IsDragMoveArea。

### ISSUE THREAD

**Issue by HeShiwen** [Panuon/Panuon.WPF.UI#190]
在窗口设置为IsDragMoveArea="True"时，Slider无法正常滑动只能点击。此故障必须在窗口非最大化时触发。
并且设置项目DisableDragMove的优先级低于IsDragMoveArea。表现为即使关闭窗口拖拽，窗口仍然算作可拖拽区域，从而进行拖拽。这个不一定是bug，但是不符合我的直觉。

**Comment by Mochengvia** [comment]
1. 你需要在Slider上设置 `pu:WindowX.IsDragMoveArea=False` 。我已经在Samples上测试了它，一切正常。所有位于标题栏区域且需要鼠标交互的控件都应设置这个属性。
![图片](https://github.com/Panuon/Panuon.WPF.UI/assets/23360265/3abbb3c1-ef10-4454-8ade-7bcafe6cd9b5)
2. 此问题已经确认，已在 `1.1.15.7` 版本中修复，请注意更新。

**Comment by HeShiwen** [comment]
感谢维护！Panuon很好用。

发件人: ***@***.***>
发送时间: 2023年8月26日 0:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Panuon/Panuon.WPF.UI] 在窗口设置为IsDragMoveArea="True"时，Slider无法正常滑动只能点击。并且设置项目DisableDragMove的优先级低于IsDragMoveArea。 (Issue #190)


  1.  你需要在Slider上设置 pu:WindowX.IsDragMoveArea=False 。我已经在Samples上测试了它，一切正常。所有位于标题栏区域且需要鼠标交互的控件都应设置这个属性。
[图片]<https://user-images.githubusercontent.com/23360265/263329576-3abbb3c1-ef10-4454-8ade-7bcafe6cd9b5.png>
  2.  此问题已经确认，已在 1.1.15.7 版本中修复，请注意更新。

―

**Comment by HeShiwen** [comment]
你好，我发现了与此类似的问题。在打开窗口的IsDragMoveArea之后，ScrollViewer的滚动条无法拖拽。

何世文

发件人: ***@***.***>
发送时间: 2023年8月26日 0:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Panuon/Panuon.WPF.UI] 在窗口设置为IsDragMoveArea="True"时，Slider无法正常滑动只能点击。并且设置项目DisableDragMove的优先级低于IsDragMoveArea。 (Issue #190)


  1.  你需要在Slider上设置 pu:WindowX.IsDragMoveArea=False 。我已经在Samples上测试了它，一切正常。所有位于标题栏区域且需要鼠标交互的控件都应设置这个属性。
[图片]<https://user-images.githubusercontent.com/23360265/263329576-3abbb3c1-ef10-4454-8ade-7bcafe6cd9b5.png>
  2.  此问题已经确认，已在 1.1.15.7 版本中修复，请注意更新。

―

**Comment by Mochengvia** [comment]
听起来似乎是错误地使用了IsDragMoveArea属性。
如果是希望让内容区域也可以拖拽，应该使用这种结构：
```
<Grid>
  <Border Background="Transparent" pu:WindowX.IsDragMoveArea="True" />
  ...
</Grid>
```
不要将pu:WindowX.IsDragMoveArea直接放在容器上，这会导致鼠标无法操作控件。

**Comment by HeShiwen** [comment]
多谢解答！

发件人: ***@***.***>
发送时间: 2023年8月26日 15:45
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Panuon/Panuon.WPF.UI] 在窗口设置为IsDragMoveArea="True"时，Slider无法正常滑动只能点击。并且设置项目DisableDragMove的优先级低于IsDragMoveArea。 (Issue #190)


听起来似乎是错误地使用了IsDragMoveArea属性。
如果是希望让内容区域也可以拖拽，应该使用这种结构：

<Grid>

  <Border Background="Transparent" pu:WindowX.IsDragMoveArea="True" />

  ...

</Grid>

不要将pu:WindowX.IsDragMoveArea直接放在容器上，这会导致鼠标无法操作控件。

―
