### ISSUE TITLE
Menu 相关问题

### ISSUE THREAD

**Issue by Hakoyu** [Panuon/Panuon.WPF.UI#192]
1. `Menu` 的 `MenuItem` 自带阴影 但无法使用 `MenuHelper` 进行设置
    ![HKW 2023 0925 220254](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/1f35aacb-45d4-473b-b899-37fa4b8b3046)
2. `TopLevelItems` 似乎要比 `Menu` 本身要大一些
    ![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/e76378fc-8222-4d1e-aa48-5f9eb0869afb)
3. `Submenu` 无法设置边框颜色 希望添加此功能
    ![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/15f10f91-4be7-4aa1-a14e-8f04cdc78f72)
    ![image](https://github.com/Panuon/Panuon.WPF.UI/assets/48956359/bd034e0f-7e1d-4378-8fd5-225d0c7c99d9)

**Comment by Hakoyu** [comment]
已成功设置 谢谢

**Comment by Mochengvia** [comment]
在当前版本中，Menu的效果一切正常。以运行时效果为准，不要依赖于设计器的显示效果
```
<Menu Height="NaN"
      BorderThickness="0">
    <MenuItem Header="Item 1" />
    <MenuItem Header="Item 2" />
    <MenuItem Header="Item 3" />
</Menu>
```
![图片](https://github.com/Panuon/Panuon.WPF.UI/assets/23360265/720a0a35-a411-473a-aef8-5fd819dc4f79)

**Comment by Hakoyu** [comment]
行
