### ISSUE TITLE
TabControl  两层嵌套  第二层初始化显示有问题 

### ISSUE THREAD

**Issue by yhzou91** [Panuon/Panuon.WPF.UI#193]
TabControl  两层嵌套  第二层初始化显示有问题（高度初始化异常），需要窗体缩放后显示正常。（.NET 6）
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/47960924/69fff75a-b341-4397-9984-13c5b6a29082)

**Comment by Mochengvia** [comment]
此问题已经确认为BUG
可以暂时通过设置TabControlHelper.HeaderPanelAlignment=Stretch来解决

**Comment by Mochengvia** [comment]
问题已经修复
