### ISSUE TITLE
分页出现多个…

### ISSUE THREAD

**Issue by guaicaiboshi** [Panuon/Panuon.WPF.UI#194]
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/2748771/61411276-c9ab-4300-8a89-9b3d4132d112)

**Comment by Mochengvia** [comment]
在设计上是故意这样做的，这样可以使分页控件的整体长度不会出现变化，使鼠标能在点击后仍处于点击前的位置而不会出现偏移
