### ISSUE TITLE
DataGrid 默认样式在低刷新率下显示异常（边框、背景色等）

### ISSUE THREAD

**Issue by yhzou91** [Panuon/Panuon.WPF.UI#195]
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/47960924/f4d48a22-3e47-4108-8f64-0ef6b8ec05b6)
在高刷新率的屏幕上显示正常，边框、背景色都很明显，在低刷新率下就一片白

**Comment by Mochengvia** [comment]
这个问题是第一次听到..
设备的刷新率是多少？原生控件会出问题吗

**Comment by yhzou91** [comment]
不好意思，是外接显示器显示颜色的问题
