### ISSUE TITLE
1.标题栏的SearchBox命名不能引用；2.设置其Text之后光标显示在最前端，无法用鼠标更改位置

### ISSUE THREAD

**Issue by HeShiwen** [Panuon/Panuon.WPF.UI#197]
1.在XAML文件中使用pu:SearchBox x:Name="SchBoxOfArt"，并不能在对应的.cs文件中引用此名称。
此定义在以下位置内部：
<pu:WindowXCaption.HeaderTemplate>
    <DataTemplate>
            <Grid>
2.通过sender引用此SearchBox，使用searchBox.Text = (string)xxx;这种语句设置显示的文字之后，文字正常显示，并且候选列表弹出。
但是文字框的光标出现在文字之前，并且无法用鼠标更改其位置，只能用键盘的左右按键调整，导致在运行时修改此文字不是很顺畅。
另外，是否有方法在设置searchBox.Text时不弹出候选列表？

感谢！

**Comment by Mochengvia** [comment]
1 问题出于使用错误 DataTemplate中的内容无法直接访问
2 无法更改位置的问题已经修复
由于时间太久，关闭此issue。
