### ISSUE TITLE
右键菜单显示位置不对

### ISSUE THREAD

**Issue by Dstary** [Panuon/Panuon.WPF.UI#198]
![Snipaste_2023-11-26_18-49-48](https://github.com/Panuon/Panuon.WPF.UI/assets/41058811/53c774d7-9050-4273-ba82-c7b85ad8dbe8)
如图所示，ContextMenu菜单显示不全

**Comment by Mochengvia** [comment]
是最新的Panuon.WPF.UI版本吗？
请附上代码
