### ISSUE TITLE
在使用  MessageBoxX.Show 弹窗，倒计时 发现一个问题

### ISSUE THREAD

**Issue by zflq2002** [Panuon/Panuon.WPF.UI#199]
MessageBoxX.Show("", "", MessageBoxButton.OK, MessageBoxIcon.Warning, DefaultButton.YesOK, 3);

<pu:MessageBoxXSettings.InverseButtonsSequence>True</pu:MessageBoxXSettings.InverseButtonsSequence>
![2](https://github.com/Panuon/Panuon.WPF.UI/assets/47547893/894563b8-596a-4b3d-a91f-fbf7e494c93c)

<pu:MessageBoxXSettings.InverseButtonsSequence>false</pu:MessageBoxXSettings.InverseButtonsSequence>
![1](https://github.com/Panuon/Panuon.WPF.UI/assets/47547893/56e1f440-647d-4a16-9c57-6429582254e8)

**Comment by Lilyltt** [comment]
Will be fixed in next version😀
