### ISSUE TITLE
点击输入框没有聚焦，手动设置聚焦之后，在输入的时候会失焦（必现有时候输入4个字符，有时候输入两个字符就出现失焦情况）

### ISSUE THREAD

**Issue by thomswang** [Panuon/Panuon.WPF.UI#203]
https://github.com/Panuon/Panuon.WPF.UI/assets/15908342/913b89de-6df7-4d39-aeef-e6f848574ac8

**Comment by Mochengvia** [comment]
此库仅用于处理pu中出现的问题，外部开发不在讨论范围内。如果samples中的项目也出现了这个问题，请留言。
