### ISSUE TITLE
有技术qq群或者微信群吗？

### ISSUE THREAD

**Issue by wangjunjx8868** [Panuon/Panuon.WPF.UI#204]
有技术qq群或者微信群吗？

**Comment by Mochengvia** [comment]
有啊，QQ群718778191
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年2月1日 08:57
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [Panuon/Panuon.WPF.UI] 有技术qq群或者微信群吗？ (Issue #204)
        
      
    
  

有技术qq群或者微信群吗？
