### ISSUE TITLE
Toast 消息提示如果快速连续弹出会出现重叠现象，是否可以考虑去掉之前的？

### ISSUE THREAD

**Issue by jsrgckf** [Panuon/Panuon.WPF.UI#211]
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/27858634/7515cc1e-ba44-4981-a405-662bc211b5dc)
类似这样
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/27858634/3fd9b61e-a236-463e-a259-c974f5e38e9b)

**Comment by Mochengvia** [comment]
这个功能将在下个版本提供。
可以通过在任意静态构造器中调用 `pu:ToastSettings.ClearBeforeShow = true;` ，或在App.xaml中添加 `<pu:ToastSettings x:Key="toastSettings" ClearBeforeShow="True" />` 节点来启用此选项。
