### ISSUE TITLE
Panuon.WPF.UI 1.2.0 版本 生成 net8的dll 缺少资源文件，启动报错

### ISSUE THREAD

**Issue by zflq2002** [Panuon/Panuon.WPF.UI#212]
Panuon.WPF.UI 1.2.0 版本 生成 net8的dll 缺少资源文件，启动报错
![60E1157F-2E5C-4f98-ADEA-A5166EFCB845](https://github.com/Panuon/Panuon.WPF.UI/assets/47547893/f84d724c-bd6c-471f-b9a9-3993c604155e)

**Comment by Mochengvia** [comment]
问题已经修复
