### ISSUE TITLE
ListBoxHelper.ItemsRemoveButton双击判定可能存在问题

### ISSUE THREAD

**Issue by HeShiwen** [Panuon/Panuon.WPF.UI#217]
ListBoxHelper.ItemsRemoveButton双击时会先触发单击事件，移除该Item，随后触发Item的双击事件。触发已经被移除的Item的双击事件时，此Item为Null，这可能会造成问题。这个问题可以从Item双击事件中加入Null判定解决，但是此ListBoxHelper.ItemsRemoveButton从直觉上应该没有双击事件。
希望讨论此问题，并确定是否需要修改。

**Comment by Mochengvia** [comment]
我尝试在RemoveButton上以最快的速度双击，这只会连续移除两个子项，并且没有触发ListBoxItem的双击事件。
怎样操作才能在RemoveButton上双击？或者说，触发的是ListBox的双击事件，而不是ListBoxItem的双击事件？
请告诉我更多信息。

**Comment by HeShiwen** [comment]
不好意思回复这么晚。我的程序中在RemoveButton上双击，触发的是RemoveButton的单击事件，从而移除此Item，并且触发该ListBox的Item双击事件，导致引用已经被移除的Item，造成null判定错误。
________________________________
发件人: 末城via ***@***.***>
发送时间: 2024年5月31日 1:29
收件人: Panuon/Panuon.WPF.UI ***@***.***>
抄送: HeShiwen ***@***.***>; Author ***@***.***>
主题: Re: [Panuon/Panuon.WPF.UI] ListBoxHelper.ItemsRemoveButton双击判定可能存在问题 (Issue #217)


我尝试在RemoveButton上以最快的速度双击，这只会连续移除两个子项，并且没有触发ListBoxItem的双击事件。
怎样操作才能在RemoveButton上双击？或者说，触发的是ListBox的双击事件，而不是ListBoxItem的双击事件？
请告诉我更多信息。

―
