### ISSUE TITLE
ListBoxHelper.ItemClick  触发按键问题

### ISSUE THREAD

**Issue by LIXianSenQwQ** [Panuon/Panuon.WPF.UI#218]
ListBoxHelper.ItemClick 事件左键、右键、鼠标两个侧键都可以触发。
当我的itemClick触发会调转到其他Page页面，而frame导航默认 鼠标侧键是返回、前进。
所以当按下侧键的时候会发生冲突，切换到其他Page 瞬间切换回来。
能否加上 ItemClick的触发方式。
![ListBoxHelper ItemClick跟Frame导航冲突](https://github.com/Panuon/Panuon.WPF.UI/assets/57521037/9050ff9c-72ad-4dc6-8b7f-4815e024a4df)

**Comment by Mochengvia** [comment]
此bug将在近期的版本中修复
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月16日 ***@***.***>***@***.***>主题[Panuon/Panuon.WPF.UI] ListBoxHelper.ItemClick 触发按键问题 (Issue #218)
ListBoxHelper.ItemClick 事件左键、右键、鼠标两个侧键都可以触发。
当我的itemClick触发会调转到其他Page页面，而frame导航默认 鼠标侧键是返回、前进。
所以当按下侧键的时候会发生冲突，切换到其他Page 瞬间切换回来。
能否加上 ItemClick的触发方式。
ListBoxHelper.ItemClick.Frame.gif (view on web)
