### ISSUE TITLE
DatetimePicker选择时间日期没有立即更新

### ISSUE THREAD

**Issue by Dstary** [Panuon/Panuon.WPF.UI#219]
![1714132632255](https://github.com/Panuon/Panuon.WPF.UI/assets/41058811/3363bfec-1013-40f6-9a7f-b78ac2d99045)
如图所示，把开始日期设置为结束日期最小值，分2种情况，第一种，当把结束日期设置为开始日期的最大值时，选择了开始日期后，再改变结束日期时开始日期会变为结束日期的时间，绑定为oneway模式。第二种，如图不设置开始日期最大值，当选择开始日期大于结束日期时，结束日期的文本会改变为开始日期，即绑定的最大日期。但是没有更新ViewModel里面的数据。即使设置了立即更新也没有更新。

**Comment by Mochengvia** [comment]
在你的第二种情况中，`MinDateTime` 的变化将触发 `SelectedDateTime` 属性的 `CoerceValue` 强制回调。
很遗憾，即使是WPF自带的这个方法，它也不会修改数据源的值，这就是为什么你无法在ViewModel中捕获 `EndDateTime` 属性的 `set` 方法。
这个问题暂时没有办法解决。
在 Slider 控件中也存在同样的问题，使 `Minimum` 的值大于 `Value` 并不会触发 `Value` 的数据源值发生变化。
你可以在这里看到原因：https://stackoverflow.com/questions/32060975/slider-value-does-not-update-after-changing-minimum-and-maximum

无论用户选择什么，我都建议你在储存用户数据时做好最后的检查，避免出现 `EndDateTime` 小于 `StartDateTime` 这种情况。
