### ISSUE TITLE
WindowX窗口最大化问题

### ISSUE THREAD

**Issue by Yezhicong** [Panuon/Panuon.WPF.UI#220]
使用WindowX窗口时，通过双击标题栏或者点击最大化按钮，窗口最大化正常，但是如果是拖动窗口到屏幕最上方后最大化，窗口底部会出现一条白边，如下图
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/44610328/b7319826-d902-4294-9337-3c9765abb5f9)
通过点击最大化按钮后的窗口如下图
![image](https://github.com/Panuon/Panuon.WPF.UI/assets/44610328/31598d13-21a8-4af4-b35c-0bb401ce0a31)

**Comment by Mochengvia** [comment]
暂时没有收到同类似的错误反馈。
这种现象通常更容易出现在精简版Windows上，也可能是某个版本的Windows出现问题。如果在其他计算机上运行也有这种问题，可以将运行的Windows版本在这里留言。

**Comment by Yezhicong** [comment]
因为我用了透明的通知栏，才发现了这个现象，不透明的通知栏就发现不了这个问题的

**Comment by Mochengvia** [comment]
我的Windows也打开了透明效果，但没有出现这种情况，我猜是系统版本的原因
