### ISSUE TITLE
在界面使用AvalonDock控件后, 弹窗的WindowX 关闭后不能隐藏遮罩层. 

### ISSUE THREAD

**Issue by bobbydog** [Panuon/Panuon.WPF.UI#221]
在界面引入AvalonDock后, WindowX的弹窗关闭仍会有遮罩层,即使设了InteropOwnersMask为False,但没有生效
 `<pu:MessageBoxXSettings.WindowXStyle>
     <Style TargetType="pu:WindowX"
        BasedOn="{StaticResource {ComponentResourceKey ResourceId=WindowXStyle, TypeInTargetAssembly={x:Type pu:MessageBoxX}}}">
         <Setter Property="SizeToContent"
             Value="Manual" />
         <Setter Property="Width"
             Value="400" />
         <Setter Property="Height"
             Value="200" />
         <Setter Property="InteropOwnersMask" Value="False" />
         <Setter Property="Foreground"
             Value="White" />
         <Setter Property="Background"
             Value="#383838" />
         <Setter Property="BorderBrush"
             Value="#363636" />
         <Setter Property="pu:WindowXCaption.CloseButtonStyle" Value="{StaticResource btn-win-close}" />
     </Style>
 </pu:MessageBoxXSettings.WindowXStyle>`

![image](https://github.com/Panuon/Panuon.WPF.UI/assets/17490587/78b32603-aa98-4aef-b931-4520286b3e87)

`<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="*"/>
    </Grid.RowDefinitions>
<StackPanel Grid.Row="0" >
    <Button Content="aaa"  Click="ReadProject_Click" />
</StackPanel>
    <avalonDock:DockingManager Grid.Row="1" Margin="0 5">
        <avalonDock:LayoutRoot>
            <avalonDock:LayoutPanel Orientation="Horizontal">
                <avalonDock:LayoutAnchorablePane  DockWidth="3*" >
                    <avalonDock:LayoutAnchorable Title="{StaticResource Key_屏体结构}" CanHide="False" CanAutoHide="False"  CanClose="False" CanMove="False" CanFloat="False"  >
                        
                    </avalonDock:LayoutAnchorable>
                </avalonDock:LayoutAnchorablePane>
            </avalonDock:LayoutPanel>
        </avalonDock:LayoutRoot>
    </avalonDock:DockingManager>
</Grid>`

`private void OpenProject_Click(object sender, RoutedEventArgs e)
{
     _ = MessageBoxX.Show(Window.GetWindow(sender), "Close Fail", "Warning", MessageBoxIcon.Warning, DefaultButton.YesOK);
    Window.GetWindow(sender).Activate();
}`

**Comment by Mochengvia** [comment]
Hi，我看到你在MessageBoxXSettings.WindowXStyle中设置了InteropOwnersMask，这是无效的。正确的设置方法如下：
```
<pu:MessageBoxXSettings x:Key="xxx" InteropOwnersMask="False" ... >
</pu:MessageBoxXSettings>
```
这应该不会再显示窗体的遮罩层。
AvalonDock使用窗体作为容器，且该窗体的Owner为当前的主窗体，这会导致OwnedWindows始终不为空，因此WindowX不会自动隐藏遮罩层。使用上述代码应该能解决这个问题。
