### ISSUE TITLE
Timeline的ItemsHeader存在多项属性没有效果

### ISSUE THREAD

**Issue by Sandf123hehe** [Panuon/Panuon.WPF.UI#238]
ItemsHeaderCornerRadius、ItemsHeaderBorderBrush、ItemsHeaderBorderThickness、ItemsHeaderBackground、ItemsHeaderHeight、ItemsHeaderPlacement、ItemsHeaderShadowColor

**Comment by Mochengvia** [comment]
此bug已修复
