### ISSUE TITLE
起动Samples时报错：XDG0008	命名空间“https://opensource.panuon.com/wpf”中不存在“SharedResourceDictionary”名称。

### ISSUE THREAD

**Issue by ch-kail** [Panuon/Panuon.WPF.UI#254]
背景：
1.打开Samples解决方案
2.将Samples设为起动项目
3.启动

问题（visual studio报错）：
XDG0008	命名空间“https://opensource.panuon.com/wpf”中不存在“SharedResourceDictionary”名称。
XLS0414	未找到类型“pw:SharedResourceDictionary”。请确保不缺少程序集引用并且已生成所有引用的程序集。
XDG0008	命名空间“clr-namespace:Panuon.WPF.UI”中不存在“WindowX”名称。
XDG0008	命名空间“clr-namespace:Panuon.WPF.UI.Internal.Resources”中不存在“StyleKeys”名称。

**Comment by ch-kail** [comment]
visual studio 版本为2019

**Comment by Mochengvia** [comment]
这个问题是nuget还原问题导致的，一般来说需要数次清理解决方案和重新生成方案就能解决。
为了方便使用，我刚刚在最新的代码中移除了nuget包，改为直接引用dll
拉取最新的代码就可以了

**Comment by ch-kail** [comment]
感谢！
