### ISSUE TITLE
RingProgressBar控件设置PercentStringFormat属性后无论Value的值是多少进度条都是满的

### ISSUE THREAD

**Issue by ch-kail** [Panuon/Panuon.WPF.UI#255]
RingProgressBar属性和style设置：
<pu:RingProgressBar Grid.Row="1"
                    Margin="0,20,0,0"
                    Style="{StaticResource RingStandardProgressBarStyle}"
                    Value="15.3"
                    PercentStringFormat="P2"
                    GeneratingPercentText="RingProgressBar_GeneratingPercentText" />

<Style x:Key="RingStandardProgressBarStyle"
               TargetType="pu:RingProgressBar">
            <Setter Property="Minimum"
                    Value="0" />
            <Setter Property="Maximum"
                    Value="100" />
            <Setter Property="Width"
                    Value="170" />
            <Setter Property="Height"
                    Value="170" />
            <Setter Property="FontSize"
                    Value="20" />
            <Setter Property="BorderThickness"
                    Value="18" />
            <Setter Property="BorderBrush"
                    Value="#22FFFFFF" />
            <Setter Property="BorderBrush"
                    Value="#226CBCEA" />
            <Setter Property="Foreground"
                    Value="#6CBCEA" />
            <Setter Property="IsPercentVisible"
                    Value="True" />
            <Setter Property="ShadowColor"
                    Value="#6CBCEA" />
            <Setter Property="pu:ShadowHelper.ShadowDepth"
                    Value="5" />
            <Setter Property="pu:ShadowHelper.BlurRadius"
                    Value="15" />
        </Style>

**Comment by ch-kail** [comment]
visual studio预览效果是正确的：
![image](https://github.com/user-attachments/assets/1f86aeaa-78b8-4766-8468-235d71b9c4fd)

运行效果错误：
![image](https://github.com/user-attachments/assets/bd742617-9bf8-4693-8f00-37da08c0925b)

**Comment by Mochengvia** [comment]
Maximum的默认值是10。不要漏掉
```C#
Maximum="100"
```
属性

**Comment by ch-kail** [comment]
问题已解决，此前测试时GeneratingPercentText事件绑定了下面这个方法设置了Value的值
        private void RingProgressBar_GeneratingPercentText(object sender, GeneratingPercentTextRoutedEventArgs e)
        {
            RingProgressBar sender1 = (RingProgressBar)sender;
            sender1.Value = 150;
        }
