### ISSUE TITLE
Panuon.WPF.UI 1.2.4.3 运行报错，Could not load file or assembly 'Panuon.WPF, Version=1.1.2.0

### ISSUE THREAD

**Issue by zflq2002** [Panuon/Panuon.WPF.UI#276]
![zzzzz](https://github.com/user-attachments/assets/fe56b1ca-30c6-4384-82bd-d67634697cf4)

**Comment by Lilyltt** [comment]
csproj有个setting ProduceReferenceAssembly 设置为true

**Comment by Mochengvia** [comment]
> csproj有个setting ProduceReferenceAssembly 设置为true

@Lilyltt  应该不是这个问题 我在看

**Comment by Mochengvia** [comment]
> ![zzzzz](https://private-user-images.githubusercontent.com/47547893/369731948-fe56b1ca-30c6-4384-82bd-d67634697cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzY2NDcsIm5iZiI6MTcyNzA3NjM0NywicGF0aCI6Ii80NzU0Nzg5My8zNjk3MzE5NDgtZmU1NmIxY2EtMzBjNi00Mzg0LTgyYmQtZDY3NjM0Njk3Y2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZWRmMWNhZWMwOWM2YTI0YWQzNzFiMmY4YWU5YmVkMmViZTFiNTc3YjE5MGNhNWJhN2U2ZTdiZjk3NmFhYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wT55Mv8s2lcZ4TI_lSja7GJHAJRlaoNkPCmBW4jGIqo)

是版本问题 稍等我重新发个版

**Comment by Mochengvia** [comment]
@zflq2002 新版本1.2.4.4已发布
