### ISSUE TITLE
多级menu的样式问题

### ISSUE THREAD

**Issue by 1029543947** [Panuon/Panuon.WPF.UI#279]
![image](https://github.com/user-attachments/assets/a3f8e74a-df08-47f7-a62c-a02902ba1015)
多级menu时后面的几级menu样式该怎么继承父级的样式

**Comment by Mochengvia** [comment]
![图片](https://github.com/user-attachments/assets/217291b8-394f-4982-926f-4b3be53fa389)

通常情况下无需多余的设置即可自动继承样式。
如需帮助，请务必提供源代码。

```
<Menu Height="30" pu:MenuHelper.SubmenuItemsHoverBackground="Blue">
    <MenuItem Header="Item 1">
        <MenuItem Header="Item 1-1">
            <MenuItem Header="Item 1-1-1">
                <MenuItem Header="Item 1-1-1-1" />
            </MenuItem>
        </MenuItem>
    </MenuItem>
</Menu>
```
