### ISSUE TITLE
[Bug]: 在pendingbox转圈执行一个4分钟的任务后, 在弹messagebox会程序崩溃, 配额不足，无法处理此命令

### ISSUE THREAD

**Issue by bobbydog** [Panuon/Panuon.WPF.UI#296]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我确认我使用了Panuon.WPF.UI,而不是Panuon.WPF.Silver等先前项目
- [X] 我已经附带了相关错误截图,确保问题准确且可复现

### 所使用的Panuon.WPF.UI库版本号

V2.2.20

### 发生了什么

在pendingbox转圈执行一个4分钟的任务后, 在弹messagebox会报错 System.ComponentModel.Win32Exception:“配额不足，无法处理此命令。” 然后退出

线程 '[线程已销毁]' (17400) 已退出，返回值为 0 (0x0)。
未经处理的异常:  System.ComponentModel.Win32Exception: 配额不足，无法处理此命令。
   在 MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   在 System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
程序“[17236] Samples.exe”已退出，返回值为 0 (0x0)。

### 重现步骤

 private async void BtnTestPendingBox_Click(object sender, RoutedEventArgs e)
 {
     var handler = PendingBox.Show(this, "PendingBox style configuration is placed in App.xaml.", "Caption", false);
     DoTask();
     handler.Close();
     MessageBoxX.Show(this, "Finish", "Tips", MessageBoxIcon.Info, DefaultButton.YesOK, 5);
     //handler.Cancelling += ...
     //handler.Close();
 }

 public void DoTask()
 {
     var waitingTask = Task.Delay(TimeSpan.FromMinutes(4));
     waitingTask.Wait();
 }

**Comment by Mochengvia** [comment]
请注意：Panuon.WPF.UI的最高版本是1.2.4.8
