### ISSUE TITLE
[Bug]: 当PendingBox.Show的owner不为空时，且窗体类型是WindowsX时，PendingBox会出现在左上角

### ISSUE THREAD

**Issue by wds-g** [Panuon/Panuon.WPF.UI#300]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我确认我使用了Panuon.WPF.UI,而不是Panuon.WPF.Silver等先前项目
- [X] 我已经附带了相关错误截图,确保问题准确且可复现

### 所使用的Panuon.WPF.UI库版本号

1.2.4.8

### 发生了什么

![image](https://github.com/user-attachments/assets/65e2cced-8119-4afb-93b1-071b1839855b)
![image](https://github.com/user-attachments/assets/93850f97-57fc-4ef6-9f8c-7193da4a9f78)

### 重现步骤

我是2块屏幕

**Comment by Mochengvia** [comment]
Application.Current.MainWindow获取到的可能不是当前显示的这个窗体。建议先检查MainWindow的当前值，或直接获取当前的窗体后再传入参数
