### ISSUE TITLE
FormGroup的Orientation属性设置为Vertical之后Header无法铺满

### ISSUE THREAD

**Issue by mchudie** [Panuon/Panuon.WPF.UI#55]
`    <Grid VerticalAlignment="Top">
        <pu:FormGroup
            HeaderWidth="*"
            HorizontalHeaderAlignment="Stretch"
            Orientation="Vertical"
            >
            <pu:FormGroup.Header>
                <Border Background="Red" Height="20" MinWidth="20">
                    <TextBlock Text="此时应该铺满"/>
                </Border>
            </pu:FormGroup.Header>
            <Border Background="BlueViolet" Height="60"/>
        </pu:FormGroup>
    </Grid>`
![image](https://user-images.githubusercontent.com/7105278/160238554-3729d8b2-fe74-4acf-bde9-0b2bc7b722eb.png)

**Comment by Mochengvia** [comment]
感谢反馈。
问题已确认，将于下个版本修复
